## 1. Elementwise Function

Elementwise function adalah fungsi yang bekerja pada setiap elemen array secara terpisah. Contohnya adalah fungsi matematis bawaan NumPy seperti `np.sin`, `np.sqrt`, dan `np.exp`. Operator aritmetika (`+`, `-`, `*`, `/`, `**`) juga berjalan secara elementwise pada array dengan ukuran sama.

Konsep ini memudahkan perhitungan numerik karena tidak perlu melakukan perulangan manual. Meskipun tersedia `np.vectorize` untuk menjadikan fungsi skalar sebagai elementwise function, pendekatan tersebut biasanya lebih lambat dibandingkan operasi vektoris bawaan NumPy atau manipulasi fungsi boolean arithmetic.

##### Contoh Kode :

In [15]:
import numpy as np

# fungsi elementwise
x = np.linspace(-1, 1, 11)
print(np.round(np.sin(np.pi * x), 4))

[-0.     -0.5878 -0.9511 -0.9511 -0.5878  0.      0.5878  0.9511  0.9511
  0.5878  0.    ]


In [9]:
import numpy as np

# operator elementwise
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a * b)   # [10 40 90]

[10 40 90]


In [17]:
import numpy as np

# fungsi piecewise sederhana
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

x2 = np.linspace(-5, 5, 11)
print(pulse(x2, -2, 1, 5))

[0 0 0 1 1 1 1 1 1 0 0]


## 2. Melakukan Agregasi Beberapa Array

Agregasi pada array bertujuan merangkum nilai-nilai elemen menjadi informasi ringkas berupa skalar atau array berdimensi lebih rendah. Contoh umum adalah fungsi `sum`, `mean`, `min`, `max`, dan `std`.

Argumen `axis` mengontrol arah agregasi. Jika `axis=0`, perhitungan dilakukan sepanjang baris sehingga hasilnya per kolom. Jika `axis=1`, perhitungan dilakukan sepanjang kolom sehingga hasilnya per baris. Tanpa argumen `axis`, seluruh elemen array akan teragregasi menjadi satu nilai.

Untuk fungsi seperti `var` dan `std`, parameter `ddof` memungkinkan pemilihan antara varian populasi (`ddof=0`) atau varian sampel (`ddof=1`).

##### Contoh Kode :

In [22]:
import numpy as np

data = np.arange(1,10).reshape(3,3)
print(data)

print("Total semua elemen:", data.sum())        
print("Jumlah per kolom:", data.sum(axis=0))    
print("Jumlah per baris:", data.sum(axis=1))    

# agregasi statistik
rng = np.random.RandomState(0)
x = rng.normal(size=(5,4))
print("Rata-rata semua elemen:", x.mean())
print("Rata-rata per kolom:", x.mean(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total semua elemen: 45
Jumlah per kolom: [12 15 18]
Jumlah per baris: [ 6 15 24]
Rata-rata semua elemen: 0.5693345929456347
Rata-rata per kolom: [ 1.15670166 -0.05000108  0.56596018  0.60467762]


## 3. Melakukan Operasi dengan Logika Himpunan

NumPy menyediakan fungsi khusus untuk operasi himpunan yang bekerja secara vektoris pada array. Operasi tersebut meliputi pengujian keanggotaan, pencarian elemen unik, serta pencarian irisan, gabungan, dan selisih antarhimpunan.

Fungsi yang sering digunakan antara lain:
- `np.in1d(a, b)` untuk menghasilkan array boolean yang menunjukkan apakah elemen a terdapat dalam b.
- `np.unique(a)` untuk menghasilkan array berisi elemen unik dari a.
- `np.union1d(a, b)` untuk menghasilkan gabungan unik dari a dan b.
- `np.intersect1d(a, b)` untuk menghasilkan irisan antara a dan b.
- `np.setdiff1d(a, b)` untuk menghasilkan elemen dalam a yang tidak ada di b.

##### Contoh Kode :

In [29]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7])

print(np.in1d(a, b))         
print(np.intersect1d(a, b))  
print(np.union1d(a, b))      
print(np.setdiff1d(a, b))    

c = np.array([1,2,2,3,1,4])
print(np.unique(c))          

[False False False  True  True]
[4 5]
[1 2 3 4 5 6 7]
[1 2 3]
[1 2 3 4]


Note : Pendekatan ini efisien untuk array numerik berukuran besar, sedangkan tipe `set` bawaan Python lebih fleksibel untuk data non-numerik atau objek kompleks.