**4. Memanipulasi Array**

**Definisi:** Manipulasi array adalah proses mengubah bentuk (shape), susunan, atau elemen dari sebuah array yang sudah ada untuk disesuaikan dengan kebutuhan analisis.Operasi ini umumnya tidak mengubah data tetapi hanya cara data tersebut diinterpretasikan.

**a. Mengubah Bentuk dan Ukuran (Reshaping and Resizing)**

**Definisi:** Fungsi reshape() digunakan untuk mengubah jumlah baris dan kolom dari sebuah array tanpa mengubah total elemennya. fungsi ini hanya mengubah atribut strides dari array, bukan memodifikasi data yang tersimpan di memori.

resize() akan mengubah ukuran array secara permanen dan bisa mengisi nilai baru jika ukurannya lebih besar.`

In [7]:
import numpy as np

# Membuat array 1D dengan 12 elemen
data = np.arange(12)
print("Array awal (1x12):\n", data)

# Mengubah bentuk menjadi matriks 3 baris 4 kolom (3x4)
# Total elemen harus tetap sama (3 * 4 = 12)
data_reshaped = data.reshape(3, 4)
print("\nHasil reshape (3x4):\n", data_reshaped)

# Meratakan kembali array menjadi 1D
data_flattened = data_reshaped.flatten()
print("\nHasil flatten:\n", data_flattened)

Array awal (1x12):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Hasil reshape (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Hasil flatten:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


**b. Menggabungkan Array (Concatenate/Stacking)**

**Definisi:** Menggabungkan beberapa array menjadi satu array yang lebih besar. 

In [17]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

gabung_vertikal = np.vstack((arr1, arr2)) # Menggabungkan secara vertikal (menambah baris)
print("Gabungan Vertikal (vstack):\n", gabung_vertikal) # Hasilnya adalah matriks 4x2

gabung_horizontal = np.hstack((arr1, arr2)) # Menggabungkan secara horizontal (menambah kolom)
print("\nGabungan Horizontal (hstack):\n", gabung_horizontal) # Hasilnya adalah matriks 2x4

Gabungan Vertikal (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Gabungan Horizontal (hstack):
 [[1 2 5 6]
 [3 4 7 8]]


**c. Memisahkan Array (Splitting)**

**Definisi:** Kebalikan dari penggabungan, yaitu memecah satu array besar menjadi beberapa array yang lebih kecil. Ini dapat dilakukan dengan fungsi np.split() , np.hsplit() ,dan np.vsplit().

In [24]:
import numpy as np

arr = np.arange(16).reshape(4, 4)
print("Array Awal:\n", arr)

# Memisahkan array secara horizontal menjadi 2 bagian yang sama besar
hasil_hsplit = np.hsplit(arr, 2)
print("\nHasil hsplit menjadi 2 bagian:")
print("Bagian 1:\n", hasil_hsplit[0])
print("Bagian 2:\n", hasil_hsplit[1])

# Memisahkan array secara vertikal menjadi 4 bagian
hasil_vsplit = np.vsplit(arr, 4)
print("\nHasil vsplit menjadi 4 bagian:")
print(hasil_vsplit)

Array Awal:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Hasil hsplit menjadi 2 bagian:
Bagian 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Bagian 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Hasil vsplit menjadi 4 bagian:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


**d. Menambah dan Menghapus Elemen**

**Definisi:** NumPy menyediakan fungsi seperti np.append() , np.insert() , dan np.delete() untuk menambah atau menghapus elemen.fungsi ini tidak mengubah array asli tetapi membuat salinan baru dari array dengan ukuran yang telah diubah

In [31]:
import numpy as np

array_awal = np.array([10, 20, 30, 40, 50])
print("Array awal:", arr)

# Menambahkan elemen 60 di akhir array
arr_appended = np.append(array_awal, 60)
print("Setelah ditambah 60:", arr_appended)

# Menyisipkan elemen 25 di index ke-2
arr_inserted = np.insert(array_awal, 2, 25)
print("Setelah disisipkan 25 di index 2:", arr_inserted)

# Menghapus elemen di index ke-3 (angka 40)
arr_deleted = np.delete(array_awal, 3)
print("Setelah elemen index 3 dihapus:", arr_deleted)

# Array asli tidak berubah
print("Array asli setelah semua operasi:", array_awal)

Array awal: [10 20 30 40 50]
Setelah ditambah 60: [10 20 30 40 50 60]
Setelah disisipkan 25 di index 2: [10 20 25 30 40 50]
Setelah elemen index 3 dihapus: [10 20 30 50]
Array asli setelah semua operasi: [10 20 30 40 50]
