# Membuat Matriks

#### Dalam NumPy, matriks adalah representasi dari array dua dimensi. Ada banyak cara untuk membuat matriks, bergantung pada data yang Anda miliki atau pola yang Anda butuhkan.

#### Definisi : Matriks adalah array dengan dua dimensi, sering digunakan untuk mewakili struktur data tabel seperti baris dan kolom. Di NumPy, ini adalah objek ndarray dengan ndim (jumlah dimensi) sama dengan 2.

#### Berikut adalah beberapa cara umum untuk membuat matriks:
#### Dari list Python : Anda bisa mengubah list Python yang berisi list lain (merepresentasikan baris) menjadi matriks NumPy.

In [55]:
import numpy as np

# Membuat matriks 2x3 dari list bersarang
list_bersarang = [[1, 2, 3], [4, 5, 6]]
matriks_a = np.array(list_bersarang)

print(f"Matriks A:\n{matriks_a}")
print(f"Dimensi matriks A: {matriks_a.ndim}")
print(f"Bentuk matriks A: {matriks_a.shape}")

Matriks A:
[[1 2 3]
 [4 5 6]]
Dimensi matriks A: 2
Bentuk matriks A: (2, 3)


### - Matriks nol dan satu : Anda dapat membuat matriks yang diisi dengan nilai konstan, seperti nol atau satu, dengan menentukan dimensinya.

In [50]:
import numpy as np

# Membuat matriks 3x3 yang diisi nol
matriks_nol = np.zeros((3, 3))
print(f"Matriks Nol 3x3:\n{matriks_nol}")

# Membuat matriks 2x4 yang diisi satu
matriks_satu = np.ones((2, 4))
print(f"\nMatriks Satu 2x4:\n{matriks_satu}")

Matriks Nol 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriks Satu 2x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### - Matriks identitas : Matriks identitas adalah matriks persegi yang memiliki nilai satu di diagonalnya dan nol di tempat lain.

In [48]:
import numpy as np

# Membuat matriks identitas 4x4
matriks_identitas = np.identity(4)
print(f"Matriks Identitas 4x4:\n{matriks_identitas}")

Matriks Identitas 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### - Matriks dengan nilai diagonal tertentu : Anda dapat membuat matriks persegi dengan nilai-nilai yang Anda tentukan di diagonalnya.

In [46]:
import numpy as np

# Membuat matriks dengan nilai diagonal [10, 20, 30]
matriks_diagonal = np.diag([10, 20, 30])
print(f"Matriks Diagonal:\n{matriks_diagonal}")

Matriks Diagonal:
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


# Memanipulasi Matriks dan Operasi-Operasi Matriks

#### Setelah membuat matriks, Anda dapat memanipulasi dan melakukan berbagai operasi matematika. NumPy sangat efisien dalam melakukan operasi ini karena menggunakan ekspresi vektorisasi.

#### Definisi: Manipulasi matriks adalah proses mengubah bentuk atau isi matriks, sementara operasi matriks adalah penerapan fungsi matematika pada satu atau lebih matriks untuk menghasilkan matriks atau skalar baru.

### - Mengakses elemen dan slicing

#### Anda dapat mengakses elemen individual atau sub-matriks menggunakan indeks berbasis nol.

In [44]:
import numpy as np

matriks_b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f"Matriks B:\n{matriks_b}")

# Mengakses elemen di baris ke-2, kolom ke-3 (ingat, indeks dimulai dari 0)
print(f"\nElemen di B[1, 2]: {matriks_b[1, 2]}")

# Mengambil seluruh baris pertama
print(f"\nSeluruh baris pertama: {matriks_b[0, :]}")

# Mengambil seluruh kolom kedua
print(f"\nSeluruh kolom kedua: {matriks_b[:, 1]}")

# Mengambil sub-matriks dari baris 1-2 dan kolom 1-2
sub_matriks = matriks_b[0:2, 0:2]
print(f"\nSub-matriks:\n{sub_matriks}")

Matriks B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Elemen di B[1, 2]: 15

Seluruh baris pertama: [10 11 12]

Seluruh kolom kedua: [11 14 17]

Sub-matriks:
[[10 11]
 [13 14]]


### - Operasi Aritmatika

#### Operasi aritmatika dasar (+, -, *, /) pada matriks NumPy dilakukan secara element-wise (elemen per elemen), bukan operasi matriks standar.

In [40]:
import numpy as np

matriks_c = np.array([[1, 2], [3, 4]])
matriks_d = np.array([[5, 6], [7, 8]])

# Penjumlahan matriks (element-wise)
print(f"C + D:\n{matriks_c + matriks_d}")

# Perkalian matriks (element-wise)
print(f"\nC * D (element-wise):\n{matriks_c * matriks_d}")

# Perkalian matriks skalar
print(f"\nC * 2:\n{matriks_c * 2}")

C + D:
[[ 6  8]
 [10 12]]

C * D (element-wise):
[[ 5 12]
 [21 32]]

C * 2:
[[2 4]
 [6 8]]


### - Perkalian matriks (dot product)

#### Untuk melakukan perkalian matriks standar (dot product), Anda dapat menggunakan fungsi np.dot() atau operator @.

In [42]:
import numpy as np

matriks_c = np.array([[1, 2], [3, 4]])
matriks_d = np.array([[5, 6], [7, 8]])

# Perkalian matriks dengan np.dot()
dot_product_a = np.dot(matriks_c, matriks_d)
print(f"C . D (menggunakan np.dot):\n{dot_product_a}")

# Perkalian matriks dengan operator @
dot_product_b = matriks_c @ matriks_d
print(f"\nC @ D (menggunakan operator @):\n{dot_product_b}")

C . D (menggunakan np.dot):
[[19 22]
 [43 50]]

C @ D (menggunakan operator @):
[[19 22]
 [43 50]]


# Membuat Array Multidimensi

#### NumPy tidak hanya terbatas pada matriks dua dimensi. Anda dapat membuat array dengan dimensi apa pun, yang sering disebut tensor.

#### Definisi: Array multidimensi adalah struktur data yang dapat menyimpan data dalam lebih dari dua dimensi, seperti 3D (panjang, lebar, tinggi) atau lebih.

### - Membuat array 3 dimensi

#### Anda bisa membuat array 3D dari list bersarang yang lebih dalam, atau menggunakan fungsi khusus seperti np.random.rand().

In [38]:
import numpy as np

# Membuat array 3D dari list bersarang
array_3d_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
array_3d_a = np.array(array_3d_list)

print(f"Array 3D dari list:\n{array_3d_a}")
print(f"Dimensi: {array_3d_a.ndim}")
print(f"Bentuk: {array_3d_a.shape}")

# Membuat array 3D yang diisi angka acak
array_3d_b = np.random.rand(2, 3, 4)
print(f"\nArray 3D acak 2x3x4:\n{array_3d_b}")

Array 3D dari list:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensi: 3
Bentuk: (2, 2, 2)

Array 3D acak 2x3x4:
[[[0.37162332 0.5299344  0.05499921 0.83050913]
  [0.87172279 0.69143555 0.77134505 0.97176812]
  [0.53836273 0.35942234 0.79337193 0.63863433]]

 [[0.05668043 0.70105509 0.40199316 0.60565059]
  [0.41824925 0.29242694 0.19299766 0.60831186]
  [0.91728469 0.34403185 0.75235491 0.75013276]]]


### - Mengubah bentuk (Reshaping)

#### Anda dapat mengubah bentuk array yang sudah ada asalkan jumlah total elemennya tetap sama.

In [36]:
import numpy as np

# Membuat array 1 dimensi dengan 12 elemen
array_1d = np.arange(12)
print(f"Array 1D:\n{array_1d}")
print(f"Bentuk awal: {array_1d.shape}")

# Mengubahnya menjadi matriks 3x4
matriks_baru = array_1d.reshape(3, 4)
print(f"\nMatriks 3x4 hasil reshape:\n{matriks_baru}")
print(f"Bentuk baru: {matriks_baru.shape}")

# Mengubah matriks 3x4 menjadi array 2x2x3
array_3d_c = matriks_baru.reshape(2, 2, 3)
print(f"\nArray 3D hasil reshape:\n{array_3d_c}")
print(f"Bentuk baru: {array_3d_c.shape}")

Array 1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Bentuk awal: (12,)

Matriks 3x4 hasil reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Bentuk baru: (3, 4)

Array 3D hasil reshape:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Bentuk baru: (2, 2, 3)


### - Menggabungkan array

#### Anda dapat menggabungkan beberapa array menjadi satu array yang lebih besar.

In [34]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Menggabungkan secara vertikal (seperti menyusun baris)
gabung_vertikal = np.vstack((a, b))
print(f"Hasil gabung vertikal:\n{gabung_vertikal}")

# Menggabungkan secara horizontal (seperti menyusun kolom)
gabung_horizontal = np.hstack((a, b))
print(f"\nHasil gabung horizontal:\n{gabung_horizontal}")

Hasil gabung vertikal:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Hasil gabung horizontal:
[[1 2 5 6]
 [3 4 7 8]]
